---

-

  hosts: cent3

  tasks:

    - name: copy template to dest
      template:
        src: templates/dump_variables
        dest: /tmp/ansible_variables
     
    - name: Fetching variables
      fetch:
        src: /tmp/ansible_variables
        dest: "captured_variables/{{ ansible_hostname }}"
        flat: yes

    - name: clear variables
      file:
        path: /tmp/ansible_variables
        state: absent





...
