---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: cent3

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        update_cache: yes
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: Install Nginx
      package:
        name: nginx
        state: latest
    
    - name: Install Patch
      yum:
        name: patch
        update_cache: yes
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Patch nginx conf file on centos hosts
      patch:
        src: nginx/files/nginx.conf.centos.patch
        dest: /etc/nginx/nginx.conf
      when: ansible_distribution == "CentOS"

    - name: Creating nginx directories
      file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Creating nginx directories
      file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Copying default config
      copy:
        src: nginx/files/nginx-default.conf
        dest: /etc/nginx/sites-enabled/default

    - name: Creating sym link
      file:
        src: /etc/nginx/sites-enabled/default
        dest: /etc/nginx/sites-available/default
        state: link
    
    - name: Creating nginx directories
      file:
        path: /usr/share/nginx/html
        state: directory

    - name: Creating webpage from template
      template:
        src: nginx/templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      notify: Check HTTP


  handlers:
  
    - name: Check HTTP
      uri:
        url: http://{{ ansible_default_ipv4.address }}
        status_code: 200

# Three dots indicate the end of a YAML document
...
