---

-

  hosts: cent3

  tasks:

    - name: Registerting output
      command: "hostname -s"
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version | int >= 7
      register: command_register

    - name: install patch
      yum:
        name: patch
        state: latest
      when: command_register is changed
      
    - name: install when skipped
      apt:
        name: patch
        state: latest
      when: command_register is skipped



...

